parameters:
    # PDF of content available
    pdf_available: [ 13, 17, 20 ]

ibexa:
    system:
        admin_group:
            languages: [eng-US,eng-GB]
            content_tree_module:
                allowed_content_types: '*'
        site:
            languages: [eng-US,eng-GB]
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [770] }
        default:
            pagelayout: '@ibexadesign/pagelayout.html.twig'
        site_group:
            design: site_design
            user:
                login_template: '@ibexadesign/Security/login.html.twig'
            content_view:
                line:
                    article:
                        template: '@ibexadesign/line/article.html.twig'
                        match:
                            Identifier\ContentType: [article]
                    name_only:
                        template: '@ibexadesign/line/name_only.html.twig'
                        match:
                            Identifier\ContentType: [department,program]
                full:
                    sign:
                        template: '@ibexadesign/full/sign.html.twig'
                        match:
                            Id\Content: 61
                        controller: ibexa_query:locationQueryAction
                        params:
                            query:
                                query_type: LocationChildren
                                parameters:
                                    parentLocationId: '@=location.id'
                                assign_results_to: items
                    course:
                        controller: App\Controller\DefaultController::courseViewEnhancedAction
                        template: '@ibexadesign/full/course.html.twig'
                        match:
                            Identifier\ContentType: [course]
                    department:
                        template: '@ibexadesign/full/department.html.twig'
                        match:
                            Identifier\ContentType: [department,program]
                        controller: ibexa_query:locationQueryAction
                        params:
                            query:
                                query_type: LocationChildren
                                parameters:
                                    parentLocationId: '@=location.id'
                                assign_results_to: items
                    folder:
                        template: '@ibexadesign/full/folder.html.twig'
                        match:
                            Identifier\ContentType: [folder]
                        controller: ibexa_query:locationQueryAction
                        params:
                            query:
                                query_type: LocationChildren
                                parameters:
                                    parentLocationId: '@=location.id'
                                assign_results_to: items
                    syllabus:
                        controller: App\Controller\DefaultController::syllabusViewEnhancedAction
                        template: '@ibexadesign/full/syllabus.html.twig'
                        match:
                            Identifier\ContentType: [syllabus]
                        params:
                            availableSupportServicesId: 70
                            collegePoliciesId: 249
                            diversityEquityAndInclusionId: 181
                            gradingSchemeId: 85
                            technologyId: 180
                            bookstoreId: 177
                    running_start_syllabus:
                        controller: App\Controller\DefaultController::runningStartSyllabusViewEnhancedAction
                        template: '@ibexadesign/full/running_start_syllabus.html.twig'
                        match:
                            Identifier\ContentType: [running_start_syllabus]
                        params:
                            availableSupportServicesId: 252
                            collegePoliciesId: 52
                            diversityEquityAndInclusionId: 181
                            gradingSchemeId: 85
                            technologyId: 180
                            bookstoreId: 177

ibexa_design_engine:
    design_list:
        site_design: [site_design]
    templates_theme_paths:
        site_design:
            - '%kernel.project_dir%/templates/views/themes/site_design'
    templates_override_paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/templates/views/themes/site_design'

twig:
    globals:
        pdf_dir: /pdf
        pdf_available: '%pdf_available%'
