#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pdf:
     path: /pdf/{path}
     controller: App\Controller\PdfController::pdfViewAction
     requirements:
        path: .+

content_object_dump:
     path: /content_object_dump
     controller: App\Controller\UtilityController::contentObjectDumpAction
